name: 'changed directory'
description: 'monitor special directory to decide whether have been changed'
author: 'mingrenliu'

# Define your inputs here.
inputs:
  directories:
    description: 'monitored special directories'
    required: true
  ignore:
    description: 'what type file to be ignore'
    required: false
  separator:
    description: 'directory or file separator'
    required: false
    default: ';'
  token:
    description: 'approval token'
    required: true
# Define your outputs here.
outputs:
  matrix:
    description: 'changed directories'

runs:
  using: node16
  main: dist/index.js
